CREATE TABLE CLIENT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(1000),
    UNIT_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDERING(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDERING_DATE TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ORDERING_ITEM(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    ORDERING_ID INTEGER REFERENCES ORDERING (ID),
    AMOUNT INTEGER
);